#apiVersion: v1
#data:
#  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
#  username: cG9zdGdyZXM=
#kind: Secret
#metadata:
#  name: cluster-example-superuser
#type: kubernetes.io/basic-auth
#---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: $cluster_name
spec:
  instances: $postgres_instances
  imageName: "$postgres_default_image"

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: $barman_object_name
  enableSuperuserAccess: true

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:
    synchronous:
      method: any
      number: 1
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    pg_hba:
      - host replication all all trust
      - hostssl replication all all trust
      - hostssl replication streaming_replica all cert
      - host all all 0.0.0.0/0 md5

  storage:
    size: $postgres_storage
  walStorage:
    size: $postgres_wal_storage
  
  # Scheduling: Ensure pods spread across your 3 disks/nodes
  #affinity:
  #  nodeSelector:
  #    role: postgres-node
  #  podAntiAffinityType: required # Strict: won't start 2 pods on 1 node
  #  topologyKey: kubernetes.io/hostname

  resources:
    requests:
      memory: "${postgres_memory}"
      cpu: "${postgres_cpu}"
    limits:
      memory: "${postgres_max_memory}"
      cpu: "${postgres_max_cpu}"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ${cluster_name}
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": ${cluster_name}
  podMetricsEndpoints:
  - port: metrics
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: ${cluster_name}-ca
          key: ca.crt
      serverName: ${cluster_name}-rw
