apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: object-store
spec:
  retentionPolicy: "${barman_retention_policy}"
  configuration:
    destinationPath: s3://${s3_bucket}/
    endpointURL: http://${local_ip}:${minio_port}
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: minio-creds
        key: MINIO_SECRET_KEY
    #wal:
    #  compression: gzip
  instanceSidecarConfiguration:
    retentionPolicyIntervalSeconds: 1800
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
